/* Generated By:JavaCC: Do not edit this line. HelloWorldConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HelloWorldConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IGNORE = 1;
  /** RegularExpression Id. */
  int RESERVEDWORDABSTRACT = 2;
  /** RegularExpression Id. */
  int RESERVEDWORDDEFAULT = 3;
  /** RegularExpression Id. */
  int RESERVEDWORDRESERVEDWORDGOTO = 4;
  /** RegularExpression Id. */
  int RESERVEDWORDPACKAGE = 5;
  /** RegularExpression Id. */
  int RESERVEDWORDSYNCHRONIZED = 6;
  /** RegularExpression Id. */
  int RESERVEDWORDASSERT = 7;
  /** RegularExpression Id. */
  int RESERVEDWORDDO = 8;
  /** RegularExpression Id. */
  int RESERVEDWORDIF = 9;
  /** RegularExpression Id. */
  int RESERVEDWORDPRIVATE = 10;
  /** RegularExpression Id. */
  int RESERVEDWORDTHIS = 11;
  /** RegularExpression Id. */
  int RESERVEDWORDBOOLEAN = 12;
  /** RegularExpression Id. */
  int RESERVEDWORDDOUBLE = 13;
  /** RegularExpression Id. */
  int RESERVEDWORDIMPLEMENTS = 14;
  /** RegularExpression Id. */
  int RESERVEDWORDPROTECTED = 15;
  /** RegularExpression Id. */
  int RESERVEDWORDTHROW = 16;
  /** RegularExpression Id. */
  int RESERVEDWORDBREAK = 17;
  /** RegularExpression Id. */
  int RESERVEDWORDELSE = 18;
  /** RegularExpression Id. */
  int RESERVEDWORDIMPORT = 19;
  /** RegularExpression Id. */
  int RESERVEDWORDPUBLIC = 20;
  /** RegularExpression Id. */
  int RESERVEDWORDTHROWS = 21;
  /** RegularExpression Id. */
  int RESERVEDWORDBYTE = 22;
  /** RegularExpression Id. */
  int RESERVEDWORDENUM = 23;
  /** RegularExpression Id. */
  int RESERVEDWORDINSTANCEOF = 24;
  /** RegularExpression Id. */
  int RESERVEDWORDRETURN = 25;
  /** RegularExpression Id. */
  int RESERVEDWORDTRANSIENT = 26;
  /** RegularExpression Id. */
  int RESERVEDWORDCASE = 27;
  /** RegularExpression Id. */
  int RESERVEDWORDEXTENDS = 28;
  /** RegularExpression Id. */
  int RESERVEDWORDINT = 29;
  /** RegularExpression Id. */
  int RESERVEDWORDSHORT = 30;
  /** RegularExpression Id. */
  int RESERVEDWORDTRUE = 31;
  /** RegularExpression Id. */
  int RESERVEDWORDCATCH = 32;
  /** RegularExpression Id. */
  int RESERVEDWORDFALSE = 33;
  /** RegularExpression Id. */
  int RESERVEDWORDINTERFACE = 34;
  /** RegularExpression Id. */
  int RESERVEDWORDSTATIC = 35;
  /** RegularExpression Id. */
  int RESERVEDWORDTRY = 36;
  /** RegularExpression Id. */
  int RESERVEDWORDCHAR = 37;
  /** RegularExpression Id. */
  int RESERVEDWORDFINAL = 38;
  /** RegularExpression Id. */
  int RESERVEDWORDLONG = 39;
  /** RegularExpression Id. */
  int RESERVEDWORDSTRICTFP = 40;
  /** RegularExpression Id. */
  int RESERVEDWORDVOID = 41;
  /** RegularExpression Id. */
  int RESERVEDWORDCLASS = 42;
  /** RegularExpression Id. */
  int RESERVEDWORDFINALLY = 43;
  /** RegularExpression Id. */
  int RESERVEDWORDNATIVE = 44;
  /** RegularExpression Id. */
  int RESERVEDWORDSUPER = 45;
  /** RegularExpression Id. */
  int RESERVEDWORDVOLATILE = 46;
  /** RegularExpression Id. */
  int RESERVEDWORDCONST = 47;
  /** RegularExpression Id. */
  int RESERVEDWORDFLOAT = 48;
  /** RegularExpression Id. */
  int RESERVEDWORDNEW = 49;
  /** RegularExpression Id. */
  int RESERVEDWORDSWITCH = 50;
  /** RegularExpression Id. */
  int RESERVEDWORDWHILE = 51;
  /** RegularExpression Id. */
  int RESERVEDWORDCONTINUE = 52;
  /** RegularExpression Id. */
  int RESERVEDWORDFOR = 53;
  /** RegularExpression Id. */
  int IDENTIFIER = 54;
  /** RegularExpression Id. */
  int DECIMALINTEGER = 55;
  /** RegularExpression Id. */
  int OCTALINTEGER = 56;
  /** RegularExpression Id. */
  int HEXINTEGER = 57;
  /** RegularExpression Id. */
  int HEXLETTERS = 58;
  /** RegularExpression Id. */
  int DIGIT = 59;
  /** RegularExpression Id. */
  int NONZERO = 60;
  /** RegularExpression Id. */
  int LETTER = 61;
  /** RegularExpression Id. */
  int OCTALS = 62;
  /** RegularExpression Id. */
  int ZERO = 63;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<IGNORE>",
    "<RESERVEDWORDABSTRACT>",
    "\"default\"",
    "\"goto\"",
    "\"package\"",
    "\"synchronized\"",
    "\"assert\"",
    "\"do\"",
    "\"if\"",
    "\"private\"",
    "\"this\"",
    "\"boolean\"",
    "\"double\"",
    "\"implements\"",
    "\"protected\"",
    "\"throw\"",
    "\"break\"",
    "\"else\"",
    "\"import\"",
    "\"public\"",
    "\"throws\"",
    "\"byte\"",
    "\"enum\"",
    "\"instanceof\"",
    "\"return\"",
    "\"transient\"",
    "\"case\"",
    "\"extends\"",
    "\"int\"",
    "\"short\"",
    "\"true\"",
    "\"catch\"",
    "\"false\"",
    "\"interface\"",
    "\"static\"",
    "\"try\"",
    "\"char\"",
    "\"final\"",
    "\"long\"",
    "\"strictfp\"",
    "\"void\"",
    "\"class\"",
    "\"finally\"",
    "\"native\"",
    "\"super\"",
    "\"volatile\"",
    "\"const\"",
    "\"float\"",
    "\"new\"",
    "\"switch\"",
    "\"while\"",
    "\"continue\"",
    "\"for\"",
    "<IDENTIFIER>",
    "<DECIMALINTEGER>",
    "<OCTALINTEGER>",
    "<HEXINTEGER>",
    "<HEXLETTERS>",
    "<DIGIT>",
    "<NONZERO>",
    "<LETTER>",
    "<OCTALS>",
    "<ZERO>",
  };

}
